In [31]:
import pandas as pd

In [32]:
df_real = pd.read_csv('/layoffs.csv')

In [33]:
df_real.shape

(4562, 11)

In [34]:
df_real.head()

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Bitwise,SF Bay Area,25.0,8/12/2026,0.14,Crypto,https://www.theblock.co/news/business/2026-08-...,Unknown,154.0,United States,8/13/2026
1,Convictional,"Waterloo, Non-U.S.",NaN,8/12/2026,1.00,Other,https://betakit.com/convictional-to-shut-down-...,Series B,49.0,Canada,8/13/2026
2,LinkedIn,"Tel Aviv, Non-U.S.",50.0,8/11/2026,NaN,Recruiting,https://www.calcalistech.com/ctechnews/article...,Acquired,154.0,Israel,8/12/2026
3,Rapid7,Boston,313.0,8/10/2026,0.12,Security,https://www.bizjournals.com/boston/news/2026/0...,Post-IPO,89.0,United States,8/11/2026
4,Validient,"Sydney, Non-U.S.",NaN,8/10/2026,1.00,Other,https://www.linkedin.com/posts/ieuanleigh_my-f...,Unknown,NaN,Australia,8/11/2026

In [35]:
df_real.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4562 entries, 0 to 4561
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4562 non-null   object
 1   location             4561 non-null   object
 2   total_laid_off       2982 non-null   float64
 3   date                 4562 non-null   object
 4   percentage_laid_off  2863 non-null   float64
 5   industry             4560 non-null   object
 6   source               4559 non-null   object
 7   stage                4554 non-null   object
 8   funds_raised         4021 non-null   float64
 9   country              4560 non-null   object
 10  date_added           4562 non-null   object
dtypes: float64(3), object(8)
memory usage: 392.2+ KB

In [36]:
df_real.isnull().sum()

company                   0
location                  1
total_laid_off         1580
date                      0
percentage_laid_off    1699
industry                  2
source                    3
stage                     8
funds_raised            541
country                   2
date_added                0
dtype: int64

In [37]:
df_real=df_real.dropna(subset=['location','industry','source','stage','country'])

In [38]:
df_real.duplicated().sum()

np.int64(0)

In [39]:
df_real.shape

(4546, 11)

In [40]:
df_real

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Bitwise,SF Bay Area,25.0,8/12/2026,0.14,Crypto,https://www.theblock.co/news/business/2026-08-...,Unknown,154.0,United States,8/13/2026
1,Convictional,"Waterloo, Non-U.S.",NaN,8/12/2026,1.00,Other,https://betakit.com/convictional-to-shut-down-...,Series B,49.0,Canada,8/13/2026
2,LinkedIn,"Tel Aviv, Non-U.S.",50.0,8/11/2026,NaN,Recruiting,https://www.calcalistech.com/ctechnews/article...,Acquired,154.0,Israel,8/12/2026
3,Rapid7,Boston,313.0,8/10/2026,0.12,Security,https://www.bizjournals.com/boston/news/2026/0...,Post-IPO,89.0,United States,8/11/2026
4,Validient,"Sydney, Non-U.S.",NaN,8/10/2026,1.00,Other,https://www.linkedin.com/posts/ieuanleigh_my-f...,Unknown,NaN,Australia,8/11/2026
...,...,...,...,...,...,...,...,...,...,...,...
4557,Service,Los Angeles,NaN,3/16/2020,1.00,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4558,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.10,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4559,Panda Squad,SF Bay Area,6.0,3/13/2020,0.75,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4560,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.40,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4561,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [41]:
df_real.isnull()

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4557,False,False,True,False,False,False,False,False,False,False,False
4558,False,False,False,False,False,False,False,False,False,False,False
4559,False,False,False,False,False,False,False,False,False,False,False
4560,False,False,False,False,False,False,False,False,False,False,False
4561,False,False,False,False,True,False,False,False,False,False,False

In [42]:
df_real.isnull().sum()

company                   0
location                  0
total_laid_off         1568
date                      0
percentage_laid_off    1692
industry                  0
source                    0
stage                     0
funds_raised            531
country                   0
date_added                0
dtype: int64

In [44]:
df_real.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4546 entries, 0 to 4561
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4546 non-null   object
 1   location             4546 non-null   object
 2   total_laid_off       2978 non-null   float64
 3   date                 4546 non-null   object
 4   percentage_laid_off  2854 non-null   float64
 5   industry             4546 non-null   object
 6   source               4546 non-null   object
 7   stage                4546 non-null   object
 8   funds_raised         4015 non-null   float64
 9   country              4546 non-null   object
 10  date_added           4546 non-null   object
dtypes: float64(3), object(8)
memory usage: 555.2+ KB

In [45]:
df_real['date'].head()

0    8/12/2026
1    8/12/2026
2    8/11/2026
3    8/10/2026
4    8/10/2026
Name: date, dtype: object

In [46]:
df_real['date_added'].head()

0    8/13/2026
1    8/13/2026
2    8/12/2026
3    8/11/2026
4    8/11/2026
Name: date_added, dtype: object

In [47]:
df_real['date'] = pd.to_datetime(df_real['date'], format='%m/%d/%Y')
df_real['date_added'] = pd.to_datetime(df_real['date_added'], format='%m/%d/%Y')

In [48]:
df_real.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4546 entries, 0 to 4561
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4546 non-null   object
 1   location             4546 non-null   object
 2   total_laid_off       2978 non-null   float64
 3   date                 4546 non-null   datetime64[ns]
 4   percentage_laid_off  2854 non-null   float64
 5   industry             4546 non-null   object
 6   source               4546 non-null   object
 7   stage                4546 non-null   object
 8   funds_raised         4015 non-null   float64
 9   country              4546 non-null   object
 10  date_added           4546 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), object(6)
memory usage: 555.2+ KB

In [56]:
df_real.groupby('industry')['total_laid_off'].sum().sort_values(ascending=False)

industry
Other             115800.0
Retail            108226.0
Hardware          105200.0
Consumer           98244.0
Finance            70162.0
Transportation     67402.0
Food               52101.0
Healthcare         40298.0
Infrastructure     24835.0
Travel             24340.0
Sales              22181.0
Education          22031.0
Real Estate        21396.0
HR                 16303.0
Marketing          16245.0
Security           15054.0
Crypto             14937.0
Data               14358.0
Media              12216.0
Fitness            10146.0
Energy              9880.0
Manufacturing       9534.0
Support             8535.0
Logistics           8165.0
Recruiting          6782.0
Construction        3977.0
Aerospace           3472.0
Product             3399.0
AI                  3131.0
Legal               1116.0
Name: total_laid_off, dtype: float64

In [57]:
df_real.groupby('industry')['total_laid_off'].agg(['sum','mean','count'])

                     sum         mean  count
industry
AI                3131.0   125.240000     25
Aerospace         3472.0   231.466667     15
Construction      3977.0   331.416667     12
Consumer         98244.0   476.912621    206
Crypto           14937.0   150.878788     99
Data             14358.0   163.159091     88
Education        22031.0   196.705357    112
Energy            9880.0   352.857143     28
Finance          70162.0   195.983240    358
Fitness          10146.0   317.062500     32
Food             52101.0   321.611111    162
HR               16303.0   209.012821     78
Hardware        105200.0  1783.050847     59
Healthcare       40298.0   191.895238    210
Infrastructure   24835.0   605.731707     41
Legal             1116.0    79.714286     14
Logistics         8165.0   163.300000     50
Manufacturing     9534.0   397.250000     24
Marketing        16245.0   108.300000    150
Media            12216.0   110.054054    111
Other           115800.0   600.000000    193
Product           3399.0    87.153846     39
Real Estate      21396.0   216.121212     99
Recruiting        6782.0   150.711111     45
Retail          108226.0   447.214876    242
Sales            22181.0   352.079365     63
Security         15054.0   129.775862    116
Support           8535.0   185.543478     46
Transportation   67402.0   366.315217    184
Travel           24340.0   316.103896     77

In [58]:
df_real.groupby('country')['total_laid_off'].count()

country
Argentina                  5
Australia                 53
Austria                    6
Bahrain                    0
Belgium                    1
                        ...
United Arab Emirates       4
United Kingdom            88
United States           1822
Uruguay                    3
Vietnam                    0
Name: total_laid_off, Length: 66, dtype: int64

In [59]:
df_real.groupby('country')['company'].count().sort_values(ascending=False)

country
United States     2864
India              345
Israel             184
Canada             178
United Kingdom     159
                  ...
Peru                 1
Philippines          1
South Africa         1
Thailand             1
Ukraine              1
Name: company, Length: 66, dtype: int64

In [60]:
df_real['country'].unique()

array(['United States', 'Canada', 'Israel', 'Australia', 'UAE',
       'Singapore', 'Nigeria', 'India', 'United Kingdom', 'Seychelles',
       'Cayman Islands', 'Netherlands', 'Brazil', 'Ireland', 'Indonesia',
       'Switzerland', 'Austria', 'Germany', 'Denmark', 'Norway', 'Egypt',
       'Sweden', 'United Arab Emirates', 'Kenya', 'Cyprus', 'New Zealand',
       'Czech Republic', 'Turkey', 'Uruguay', 'Estonia', 'Japan',
       'Portugal', 'France', 'Malta', 'China', 'Pakistan', 'Spain',
       'Belgium', 'Chile', 'Lithuania', 'Poland', 'Finland', 'Romania',
       'Ghana', 'Hong Kong', 'Luxembourg', 'Mexico', 'South Korea',
       'Saudi Arabia', 'Philippines', 'Ukraine', 'Italy', 'Colombia',
       'Argentina', 'Greece', 'Malaysia', 'Hungary', 'Vietnam',
       'Thailand', 'Senegal', 'Peru', 'Bahrain', 'Russia', 'Bulgaria',
       'South Africa', 'Myanmar'], dtype=object)

In [63]:
lambda x: 'United Arab Emirates' if x == 'UAE' else x

In [64]:
df_real['country'] = df_real['country'].apply(lambda x: 'United Arab Emirates' if x == 'UAE' else x)

In [65]:
df_real['country'].unique()

array(['United States', 'Canada', 'Israel', 'Australia',
       'United Arab Emirates', 'Singapore', 'Nigeria', 'India',
       'United Kingdom', 'Seychelles', 'Cayman Islands', 'Netherlands',
       'Brazil', 'Ireland', 'Indonesia', 'Switzerland', 'Austria',
       'Germany', 'Denmark', 'Norway', 'Egypt', 'Sweden', 'Kenya',
       'Cyprus', 'New Zealand', 'Czech Republic', 'Turkey', 'Uruguay',
       'Estonia', 'Japan', 'Portugal', 'France', 'Malta', 'China',
       'Pakistan', 'Spain', 'Belgium', 'Chile', 'Lithuania', 'Poland',
       'Finland', 'Romania', 'Ghana', 'Hong Kong', 'Luxembourg', 'Mexico',
       'South Korea', 'Saudi Arabia', 'Philippines', 'Ukraine', 'Italy',
       'Colombia', 'Argentina', 'Greece', 'Malaysia', 'Hungary',
       'Vietnam', 'Thailand', 'Senegal', 'Peru', 'Bahrain', 'Russia',
       'Bulgaria', 'South Africa', 'Myanmar'], dtype=object)